### ISSUE TITLE
Set HOME: $SNAP_USER_COMMON?

### ISSUE THREAD

**Issue by ppd** [woodrow-shen/anki-snap#1]
Hi & thank you for maintaining this.

As Anki stores its media collection in `~/.local/share/Anki2`, I'm wondering whether it makes sense to treat the collection as "common data" instead. Else, it will create snapshots on every update and a possible revert of the `anki-woodrow` snap would also revert the deck collection.

By setting HOME=$SNAP_USER_COMMON, this would be easily achievable. Quite a few snaps (e.g. Firefox) employ this strategy.

**Comment by woodrow-shen** [comment]
@ppd Hi thanks for reporting it. I'll take a look and try to fix it in the next release.

**Comment by woodrow-shen** [comment]
Should be fixed with stable now
