### ISSUE TITLE
Incorrect cursor theme is used

### ISSUE THREAD

**Issue by evs-xsarus** [woodrow-shen/anki-snap#2]
I'm running the snap on Ubuntu Unity 20.04 and the incorrect cursor theme is chosen. Apparently, this must be fixed in the snap:

https://github.com/ubuntu/snapcraft-desktop-helpers/commit/da4d8f878eaeb40c1788789cd034b7142f7d6749

it means connection to the GTK common theme: https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes/-/merge_requests/26

**Comment by woodrow-shen** [comment]
The latest stable version already provides GTK common theme, enjoy!
