### ISSUE TITLE
Mark Repository as archived and remove snap from snapstore

### ISSUE THREAD

**Issue by 1Maxnet1** [woodrow-shen/anki-snap#4]
I have read that, you won't maintain this snap any further in your Update Note on the Snap Store. There is a new Community Maintained Snap available for the current Version: https://github.com/ppd/anki-ppd
 
To avoid confusion for users, I would propose to remove the outdated version from the Snapstore

**Comment by woodrow-shen** [comment]
@1Maxnet1 yes, as I had left away from snap world and job as well and I was blocked to login the store since then. Maybe the better way is to remove my all releases via talking to the Store admin.

**Comment by boukendesho** [comment]
@woodrow-shen Sorry for bother again. Can you post a request on snapcraft forum for deleting the snap?
Like this post: https://forum.snapcraft.io/t/snap-deletion-requests-localsend-uno-and-librewolf/42000
Your help will be greatly appreciated.
